on: push
name: CI

jobs:
  phpunit-php80:
    name: PHP 8.0
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-scripts

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

  phpunit-php81:
      name: PHP 8.1
      runs-on: ubuntu-latest
      container:
          image: kirschbaumdevelopment/laravel-test-runner:8.1

      steps:
          - uses: actions/checkout@v1
            with:
                fetch-depth: 1

          - name: Install composer dependencies
            run: |
                composer install --prefer-dist --no-interaction --no-scripts

          - name: Run Testsuite
            run: vendor/bin/phpunit tests/
